### ISSUE TITLE
Feature request: Option to filter out headers in response

### ISSUE THREAD

**Issue by caenrique** [NTBBloodbath/rest.nvim#70]
Hi, I was trying out this plugin for the first time and it is very useful :)

It would be nice if the headers of the response can be omitted in some way. I couldn't find any documentation on this atm so I assume it isn't implemented (correct me if I'm wrong 😅 ).
Some ideas:

- Config option to specify the headers you want
- Default "minimal" headers. Eg:  response code, content-type and charset
- new command that runs taking this config into consideration vs the normal one that returns everything

And talking about commands, it would be useful to me to have also commands, instead of just `<Plug>` mappings. I can create my own commands using those and `execute` but other people might have a similar workflow to mine

**Comment by NTBBloodbath** [comment]
Hey, yeah I think it could be useful. There are some of them that aren't very helpful imo, I'll make some tests tomorrow, my net died yesterday so I have a ton of stuff to do today haha.

I'm loving the first two ideas that you shared here. The first one sounds really cool and I love the highly customizable stuff, but second one also sounds great because the end user will only need to do something like `minimal = true` and tada!

Please let me know which one do you prefer so we can work on it soon :p}

---

> And talking about commands, it would be useful to me to have also commands, instead of just `<Plug>` mappings. I can create my own commands using those and `execute` but other people might have a similar workflow to mine

Hmm I think I didn't understood very well what you're telling me (I'm so sorry), can you please explain it a bit more? Thanks in advance

Regards

**Comment by caenrique** [comment]
Hi, what I meant was that having commands in addition to `<Plug>` bindings would be cool. I think it's just a matter of documentation, because after I wrote this I looked into the code and found the way to do it by myself :)

```vim
command! RestNvimRun lua require('rest-nvim').run()
command! RestNvimPreview lua require('rest-nvim').run(true)
command! RestNvimLast lua require('rest-nvim').last()
```
Regarding the actual topic of this PR, I just threw some ideas around but I would also be pleased by just and on/off switch for the headers, so whatever feels more appropriate  :)

And thanks for your time
