### ISSUE TITLE
:RestNvim not available.

### ISSUE THREAD

**Issue by kennycallado** [NTBBloodbath/rest.nvim#79]
Hi!
I have try to install rest.nvim plugin on nvim 0.5, however it doesn't work. There are no errors on nvim start but if I type `:RestNvim` there isn't.

I just try to follow the recomendations in the README. What I have in init.vim:

``` bash
lua require('plugins')
```
and lua/plugins.lua

``` lua
return require('packer').startup(function()
  use 'wbthomason/packer.nvim'
  use {
	 "NTBBloodbath/rest.nvim",
	 requires = { "nvim-lua/plenary.nvim" },
	 config = function()
	   require("rest-nvim").setup({
	     -- Open request results in a horizontal split
	     result_split_horizontal = false,
	     -- Skip SSL verification, useful for unknown certificates
	     skip_ssl_verification = false,
	     -- Highlight request on run
	     highlight = {
		enabled = false,
		timeout = 150,
	     },
	     -- Jump to request line on run
	     jump_to_request = false,
	   })
	 end
	}
	end
	)
```

Thanks!

**Comment by Maswor** [comment]
I'm having the same issue

**Comment by kennycallado** [comment]
I also found that the function `:lua require('rest-nvim').run()` in lvim throw an error while in nvim works. Something related with curl?

**Comment by NTBBloodbath** [comment]
Wait I think I know why it doesn't work. My apologies haha I was distracted.

rest.nvim mappings doesn't work with command-line because they're defined as plugins mappings. That means you'll need to map those commands somewhere, just keep in mind that you shouldn't use noremap when mapping them, otherwise they will not work :)

To map them you'll simply need to use `<Plug>RestNvim` as the command to be executed by your mapping and nothing more. I think README has all the available commands :)
